### ISSUE TITLE
Microsoft.Azure.Cosmos.CosmosException: 'Response status code does not indicate success: NotFound (404

### ISSUE THREAD

**Issue by wasabii** [Oriflame/cosmosdb-quartznet#12]
I get this pretty much running it out of the box. Not sure what operation it's attempting.

Diagnostics on the Exception shows it in ReplaceItemAsync.

**Comment by frantisekjandos** [comment]
Hi, 

1. What version of Cosmos client are you using.
2. Is the Quartz container already created when you start your app?

**Comment by wasabii** [comment]
Latest as of last night. Well have to go check.
Yes. I created it by hand.

**Comment by wasabii** [comment]
So, made some discoveries. If I remove my custom InstanceId setting, it proceeds, I believe, a little further. I traditionally set my InstanceId value to `{Environment.MachineName}-{Guid.NewGuid()}`. So, maybe something in the name is leaking into a Cosmos ID and not being escaped.

But, worse, if I remove my InstanceId value, I get an exception about a missing method:
```
System.MissingMethodException: Method not found: 'System.Linq.IOrderedQueryable`1<!!0> Microsoft.Azure.Cosmos.Container.GetItemLinqQueryable(Boolean, System.String, Microsoft.Azure.Cosmos.QueryRequestOptions)'.
   at Quartz.Spi.CosmosDbJobStore.Repositories.TriggerRepository.GetAllByJob(String jobName, String jobGroup)
   at Quartz.Spi.CosmosDbJobStore.CosmosDbJobStore.GetTriggersForJob(JobKey jobKey, CancellationToken cancellationToken)
```

So, I think it's going a little further. But, yeah, so, apparently they changed the signature of something in the latest Cosmos library, and this package needs to be fixed.

**Comment by wasabii** [comment]
Nothing to do with my InstanceId. That was a red herring.

It is simply the Microsoft.Azure.Cosmos package version. If I pin it down to 3.13.0 it's fine. If I let it float up to 3.17.1, it fails.

**Comment by frantisekjandos** [comment]
Yes, that it was what I thought, I have run into same issues as you :-) But had not enough time to invetigate further. Please, use the downgraded version as a workaround. If you find solution to this, it would be highly appreciated.

**Comment by wasabii** [comment]
Well the solution has to be to rebuild your nuget against the latest version.

**Comment by frantisekjandos** [comment]
I am really not sure about it, I have tried it with version 3.16.0 (see the Store version 1.0.0) and had the same issues.

**Comment by wasabii** [comment]
Well, if MS made a signature change and it appears they did, there's not much option other than to upgrade to the latest.

They probably did it in 3.17

**Comment by wasabii** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v3/commit/ecce6cfb71a44a1883bb24979e881c6a6a17587a

Yeah, they did.

**Comment by frantisekjandos** [comment]
I have upgraded to 3.17.1 and Quartz.NET also and released new NuGet.
