### ISSUE TITLE
LGPL v/s MIT license

### ISSUE THREAD

**Issue by whihathac** [Oriflame/cosmosdb-quartznet#28]
I am curious why did you opt for LGPL license even though it's a port of MongoDB (https://github.com/glucaci/mongodb-quartz-net) itself is MIT license? It requires the user to disclose source code.

**Comment by frantisekjandos** [comment]
@jvilimek Can you comment on that? I see you have updated the licence file. I have no issue changing it back to MIT, or have you @footcha?

**Comment by footcha** [comment]
I have no issues with changing back to MIT. There used to be a general idea to prefer LGPL over other public licenses. However now, we use both LPGL and MIT in different project repositories, thus the original idea is not followed anymore.

**Comment by frantisekjandos** [comment]
Please, @footcha, approve #29

**Comment by footcha** [comment]
Approved. Thank you for the change!

**Comment by frantisekjandos** [comment]
@whihathac, license has been switched to MIT.

**Comment by whihathac** [comment]
Thanks a bunch folks for quick resolution!
